import { Award, Gem, MapPin, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import Seo from '../components/Seo';
import { organizationSchema } from '../config/seoSchemas';

const copy={
 tr:{kicker:'Baklavateur — Genève',title:'Geleneği Zarafetle Sunuyoruz',lead:'Anadolu’nun tatlı mirasını Cenevre’nin seçkin sunum anlayışıyla buluşturan modern bir gurme markasıyız.',storyTitle:'Lezzetin ardındaki düşünce',story:'Baklavateur; iyi malzemenin, doğru ustalığın ve özenli sunumun bir araya geldiğinde unutulmaz bir deneyim oluşturduğuna inanır. Koleksiyonlarımızı Cenevre’de yaşayan çok kültürlü müşteriler için sade, seçkin ve güvenilir bir anlayışla hazırlıyoruz.',values:[['Seçkin malzeme','Antep fıstığı, ceviz ve özenle seçilmiş hammaddeler.'],['Ustalık','Geleneksel tekniklere saygılı, dengeli ve incelikli üretim.'],['Cenevre ruhu','Zarif ambalaj, güvenilir iletişim ve yerel teslimat odağı.'],['Kişisel hizmet','Her siparişte WhatsApp üzerinden doğrudan ve kişisel destek.']],quote:'Baklava yalnızca bir tatlı değil; paylaşmanın, misafirperverliğin ve zarafetin ifadesidir.'},
 fr:{kicker:'Baklavateur — Genève',title:'La Tradition, Présentée avec Élégance',lead:'Nous réunissons l’héritage gourmand d’Anatolie et l’élégance contemporaine de Genève.',storyTitle:'L’intention derrière chaque saveur',story:'Baklavateur croit qu’un ingrédient d’exception, un savoir-faire précis et une présentation soignée créent une expérience mémorable. Nos collections sont pensées pour une clientèle genevoise multiculturelle.',values:[['Ingrédients choisis','Pistaches d’Antep, noix et matières premières rigoureusement sélectionnées.'],['Savoir-faire','Des méthodes respectueuses de la tradition et une finition délicate.'],['Esprit genevois','Présentation élégante, communication fiable et livraison locale.'],['Service personnel','Un accompagnement direct sur WhatsApp pour chaque commande.']],quote:'Le baklava est plus qu’une pâtisserie : il exprime le partage, l’hospitalité et l’élégance.'},
 de:{kicker:'Baklavateur — Genève',title:'Tradition in Eleganter Form',lead:'Wir verbinden anatolisches Genuss-Handwerk mit der kultivierten Ästhetik Genfs.',storyTitle:'Die Idee hinter jedem Geschmack',story:'Baklavateur steht für ausgewählte Zutaten, präzises Handwerk und eine elegante Präsentation. Unsere Kollektionen richten sich an die internationale und anspruchsvolle Kundschaft in Genf.',values:[['Ausgewählte Zutaten','Antep-Pistazien, Walnüsse und sorgfältig ausgewählte Rohstoffe.'],['Handwerk','Traditionsbewusste Methoden und eine feine, ausgewogene Verarbeitung.'],['Genfer Stil','Elegante Verpackung, verlässliche Kommunikation und lokale Lieferung.'],['Persönlicher Service','Direkte Betreuung über WhatsApp bei jeder Bestellung.']],quote:'Baklava ist mehr als eine Süßigkeit – es steht für Teilen, Gastfreundschaft und Eleganz.'},
 en:{kicker:'Baklavateur — Genève',title:'Tradition, Presented with Elegance',lead:'We bring together Anatolia’s dessert heritage and Geneva’s refined contemporary sensibility.',storyTitle:'The intention behind every flavour',story:'Baklavateur believes exceptional ingredients, precise craftsmanship and thoughtful presentation create a memorable experience. Our collections are curated for Geneva’s international community.',values:[['Selected ingredients','Antep pistachios, walnuts and carefully chosen raw materials.'],['Craftsmanship','Traditional methods interpreted with balance and precision.'],['Geneva spirit','Elegant presentation, reliable communication and local delivery.'],['Personal service','Direct WhatsApp assistance with every order.']],quote:'Baklava is more than a dessert; it is an expression of sharing, hospitality and elegance.'}
};
const icons=[Gem,Award,MapPin,Sparkles];
export default function AboutPage(){
 const {i18n,t}=useTranslation(); const lang=i18n.language.slice(0,2); const c=copy[lang]||copy.tr;
 return <main className="luxury-page about-luxury-page"><Seo title={t('seo.aboutTitle')} description={t('seo.aboutDescription')} keywords={['Baklavateur Genève','Cenevre baklava markası','geleneksel baklava İsviçre']} schema={organizationSchema}/>
  <section className="luxury-page-hero about-page-hero"><div className="luxury-page-hero-overlay"/><div className="luxury-page-hero-content"><span>{c.kicker}</span><h1>{c.title}</h1><p>{c.lead}</p></div></section>
  <section className="about-story-luxury"><div className="about-story-image"><img src="/images/products/baklava-dark-plate.png" alt="Baklavateur premium baklava Genève"/></div><div className="about-story-copy"><span className="eyebrow">L’Art du Baklava</span><h2>{c.storyTitle}</h2><p>{c.story}</p><blockquote>“{c.quote}”</blockquote></div></section>
  <section className="about-values-luxury">{c.values.map(([title,text],i)=>{const Icon=icons[i];return <article key={title}><Icon size={25}/><h3>{title}</h3><p>{text}</p></article>})}</section>
 </main>;
}
